# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# Find the sum of all the even-valued terms in the sequence which do not exceed four million.


sum = 0
prev, fib = 1, 2
while !(fib > 4000000) do
  sum += fib if fib % 2 == 0
  prev, fib = fib, prev + fib
end/
puts sum #4613732
