# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# Find the sum of all the even-valued terms in the sequence which do not exceed four million.

sum, fib = 0, [1, 2]
until fib.last > 4000000 do
  f = fib.last
  sum += f if f % 2 == 0
  fib << fib[-1] + fib[-2]
end
puts sum #4613732
